# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          REACT_APP_HEROKU_URL: ${{secrets.REACT_APP_HEROKU_URL}}
      - run: npm ci
      - run: npm run build --if-present

      - uses: actions/checkout@v2
      - name: Build and deploy github pages
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          REACT_APP_HEROKU_URL: ${{secrets.REACT_APP_HEROKU_URL}}
      - run: |
          git config --global user.email gowtham.m81197@gmail.com
          git config --global user.name Gowtham Munukutla
          git remote set-url origin https://g14a:${{ secrets.GITHUB_TOKEN }}@github.com/g14a/gitsee
          npm install
          npm run deploy